### ISSUE TITLE
Can't get it to work with SVG images

### ISSUE THREAD

**Issue by Hielkio** [nuxy/baraja-js#4] opened 2023-03-11 10:43 UTC
When I load a PNG file everything works like a charm, but when I try to replace the PNG image with a SVG, nothing is showing up.
Every SVG is showing up when I go back to my original code (used DIV's and SPANs instead of UL -> LI)

- Paths are correct
- Files exist
- No console errors (like 404 not found etc.)

**Comment by nuxy** [comment] 2023-03-15 00:40
Just so I understand the issue..

- It occurs when you use SVGs with the modified HTML structure, _not the default_.
- It _does not occur_  when you use SVGs and the unmodified HTML structure.

FYI - Assuming the former case, the library is [dependent on `LI` element](https://github.com/nuxy/baraja-js/blob/master/src/baraja.js#L610) in order to work.

Sound about right?

**Comment by nuxy** [comment] 2023-03-21 19:53
Closing this issue.

If you have further questions please re-open this thread.

**Comment by Hielkio** [comment] 2023-03-25 13:02
I see that I've been unclear here.
_"Every SVG is showing up when I go back to my original code (used DIV's and SPANs instead of UL -> LI)"_

That's without using the script, thus my original, static situation. When I use the script, it just doesn't work with SVG files. 

I'm very sorry for the inconvenience! I also wanted to mention that I'm very happy (I think a lot more people) with your great work! Many thanks!

**Comment by nuxy** [comment] 2023-03-25 23:45
No inconvenience.  I just want to make sure I clearly understand what the issue is.

Do you have something online I can test? For example a [JSFiddle](https://jsfiddle.net) demo.

Note, I suspect the issue is that the SVG is not defined as a block-level element.

That said, the following rule _may_ resolve the issue.

```
svg {
  display: inline-block;
}
```

Let me know if that works for you.

**Comment by Hielkio** [comment] 2023-03-26 06:48
Thanks @nuxy !!
I think that fixed the issue :-)

Thank you very much!

**Closed as completed** 2023-03-26 16:15 UTC
Labels: question
